package com.cst438.controller;

import com.cst438.domain.*;
import com.cst438.dto.AssignmentDTO;
import com.cst438.dto.AssignmentStudentDTO;
import com.cst438.dto.GradeDTO;
import org.springframework.http.HttpStatus;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.web.bind.annotation.CrossOrigin;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RestController;
import org.springframework.web.server.ResponseStatusException;

import java.security.Principal;
import java.util.ArrayList;
import java.util.List;

@RestController
@CrossOrigin(origins = "http://localhost:3000")
public class AssignmentController {

    @Autowired
    SectionRepository sectionRepository;

    @Autowired
    AssignmentRepository assignmentRepository;

    @Autowired
    GradeRepository gradeRepository;

    @Autowired
    EnrollmentRepository enrollmentRepository;

    @Autowired
    TermRepository termRepository;

    @Autowired
    UserRepository userRepository;

    // instructor lists assignments for a section.  Assignments ordered by due date.
    // logged in user must be the instructor for the section
    @GetMapping("/sections/{secNo}/assignments")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public List<AssignmentDTO> getAssignments(
            @PathVariable("secNo") int secNo,
            Principal principal) {

        String loggedInInstructorEmail = principal.getName();

        List<Assignment> alist = assignmentRepository.findBySectionNoOrderByDueDate(secNo);

        List<AssignmentDTO> dlist = new ArrayList<>();

        for (Assignment a : alist) {
            String sectionInstructorEmail = a.getSection().getInstructorEmail();
            if (loggedInInstructorEmail.equals(sectionInstructorEmail)) {
                dlist.add(new AssignmentDTO(
                        a.getAssignmentId(),
                        a.getTitle(),
                        a.getDueDateAsString(),
                        a.getSection().getCourse().getCourseId(),
                        a.getSection().getSecId(),
                        a.getSection().getSectionNo()));
            }
        }

        return dlist;
    }

    // add assignment
    // user must be instructor of the section
    // return AssignmentDTO with assignmentID generated by database
    @PostMapping("/assignments")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public AssignmentDTO createAssignment(
            @RequestBody AssignmentDTO dto,
            Principal principal) {

        String loggedInInstructorEmail = principal.getName();
        String sectionInstructorEmail = null;

        Section s = sectionRepository.findById(dto.secNo()).orElse(null);
        if (s == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "section not found");
        }
        sectionInstructorEmail = s.getInstructorEmail();

        if (!loggedInInstructorEmail.equals(sectionInstructorEmail)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unauthorized user.");
        }

        Assignment a = new Assignment();
        a.setTitle(dto.title());
        a.setDueDate(dto.dueDate());

        if (a.getDueDate().before(s.getTerm().getStartDate())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Due date is before the start date of the course.");
        } else if (a.getDueDate().after(s.getTerm().getEndDate())) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Due date is after the end date of the course.");
        }
        if (dto.secNo() > 10) {
            throw new ResponseStatusException(HttpStatus.BAD_REQUEST, "Due date is after the end date of the course.");
        }

        a.setSection(s);
        assignmentRepository.save(a);

        return new AssignmentDTO(
                a.getAssignmentId(),
                a.getTitle(),
                a.getDueDateAsString(),
                a.getSection().getCourse().getCourseId(),
                a.getSection().getSecId(),
                a.getSection().getSectionNo());
    }

    // update assignment for a section.  Only title and dueDate may be changed.
    // user must be instructor of the section
    // return updated AssignmentDTO
    @PutMapping("/assignments")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public AssignmentDTO updateAssignment(@RequestBody AssignmentDTO dto,
                                          Principal principal) {

        String loggedInInstructorEmail = principal.getName();
        String sectionInstructorEmail = null;

        Section s = sectionRepository.findById(dto.secNo()).orElse(null);
        if (s == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "section not found");
        } else {
            sectionInstructorEmail = s.getInstructorEmail();
        }

        if (!loggedInInstructorEmail.equals(sectionInstructorEmail)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unauthorized user.");
        }

        Assignment a = assignmentRepository.findById(dto.id()).orElse(null);
        if (a == null) {
            throw  new ResponseStatusException( HttpStatus.NOT_FOUND, "assignment not found");
        }
        a.setTitle(dto.title());
        a.setDueDate(dto.dueDate());
        assignmentRepository.save(a);

        return new AssignmentDTO(
                a.getAssignmentId(),
                a.getTitle(),
                a.getDueDateAsString(),
                a.getSection().getCourse().getCourseId(),
                a.getSection().getSecId(),
                a.getSection().getSectionNo());
    }

    // delete assignment for a section
    // logged in user must be instructor of the section
    @DeleteMapping("/assignments/{assignmentId}")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public void deleteAssignment(@PathVariable("assignmentId") int assignmentId,
                                 Principal principal) {

        String loggedInInstructorEmail = principal.getName();
        String sectionInstructorEmail = null;

        Assignment a = assignmentRepository.findById(assignmentId).orElse(null);
        if (a == null) {
            throw  new ResponseStatusException( HttpStatus.NOT_FOUND, "assignment not found");
        }

        Section s = sectionRepository.findById(a.getSection().getSectionNo()).orElse(null);
        if (s == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "section not found");
        } else {
            sectionInstructorEmail = s.getInstructorEmail();
        }

        if (!loggedInInstructorEmail.equals(sectionInstructorEmail)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unauthorized user.");
        }

        assignmentRepository.delete(a);
    }


    // instructor gets grades for assignment ordered by student name
    // user must be instructor for the section
    @GetMapping("/assignments/{assignmentId}/grades")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public List<GradeDTO> getAssignmentGrades(@PathVariable("assignmentId") int assignmentId,
                                              Principal principal) {

        String loggedInInstructorEmail = principal.getName();
        String sectionInstructorEmail = null;

        Assignment a = assignmentRepository.findById(assignmentId).orElse(null);
        if (a==null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "assignment not found");
        }

        Section s = sectionRepository.findById(a.getSection().getSectionNo()).orElse(null);
        if (s == null) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "section not found");
        } else {
            sectionInstructorEmail = s.getInstructorEmail();
        }

        if (!loggedInInstructorEmail.equals(sectionInstructorEmail)) {
            throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unauthorized user.");
        }

        List<GradeDTO> dlist = new ArrayList<>();
        List<Enrollment> enrollments = enrollmentRepository.findEnrollmentsBySectionNoOrderByStudentName(a.getSection().getSectionNo());
        for (Enrollment e : enrollments) {
            Grade g = gradeRepository.findByEnrollmentIdAndAssignmentId(e.getEnrollmentId(), a.getAssignmentId());
            if (g==null) {
                // create a grade with null score.
                g = new Grade();
                g.setAssignment(a);
                g.setEnrollment(e);
                gradeRepository.save(g);
            }
            dlist.add(new GradeDTO(
                    g.getGradeId(),
                    e.getStudent().getName(),
                    e.getStudent().getEmail(),
                    a.getTitle(),
                    a.getSection().getCourse().getCourseId(),
                    a.getSection().getSecId(),
                    g.getScore()));
        }
        return dlist;
    }

    // instructor uploads grades for assignment
    // user must be instructor for the section
    @PutMapping("/grades")
    @PreAuthorize("hasAuthority('SCOPE_ROLE_INSTRUCTOR')")
    public void updateGrades(@RequestBody List<GradeDTO> dlist,
                             Principal principal) {

        String loggedInInstructorEmail = principal.getName();
        String sectionInstructorEmail = null;

        for (GradeDTO g: dlist) {
            Grade grade = gradeRepository.findById(g.gradeId()).orElse(null);
            if (grade!=null) {
                sectionInstructorEmail = grade.getAssignment().getSection().getInstructorEmail();
                if (!loggedInInstructorEmail.equals(sectionInstructorEmail)) {
                    throw new ResponseStatusException(HttpStatus.NOT_FOUND, "Unauthorized user.");
                }

                grade.setScore(g.score());
                gradeRepository.save(grade);
            } else {
                throw new ResponseStatusException(HttpStatus.NOT_FOUND, "grade not found "+ g.gradeId());
            }
        }
    }



    // student lists their assignments/grades for an enrollment ordered by due date
    // student must be enrolled in the section
    @GetMapping("/assignments")
    public List<AssignmentStudentDTO> getStudentAssignments(
            @RequestParam("studentId") int studentId,
            @RequestParam("year") int year,
            @RequestParam("semester") String semester,
            Principal principal) {

        // check that this enrollment is for the logged in user student.

        // Check that the logged-in student is requesting their own assignments
        String loggedInStudentEmail = principal.getName();
        User loggedInUser = userRepository.findByEmail(loggedInStudentEmail);
        if (loggedInUser == null || loggedInUser.getId() != studentId) {
            throw new ResponseStatusException(HttpStatus.FORBIDDEN, "Unauthorized user.");
        }

        List<AssignmentStudentDTO> dlist = new ArrayList<>();
        List<Assignment> alist = assignmentRepository.findByStudentIdAndYearAndSemesterOrderByDueDate(studentId, year, semester);
        for (Assignment a : alist) {

            Enrollment e = enrollmentRepository.findEnrollmentBySectionNoAndStudentId(a.getSection().getSectionNo(), studentId);
            if (e==null) {
                throw new ResponseStatusException(HttpStatus.NOT_FOUND, "enrollment not found studentId:"+studentId+" sectionNo:"+a.getSection().getSectionNo());
            }

            // if assignment has been graded, include the score
            Grade grade = gradeRepository.findByEnrollmentIdAndAssignmentId( e.getEnrollmentId(), a.getAssignmentId());

            System.out.println(grade);

            dlist.add(new AssignmentStudentDTO(
                    a.getAssignmentId(),
                    a.getTitle(),
                    a.getDueDate(),
                    a.getSection().getCourse().getCourseId(),
                    a.getSection().getSecId(),
                    (grade!=null)? grade.getScore(): null ));

        }
        return dlist;
    }
}
